import { Inter } from "next/font/google";
import "./globals.sass";
import BackToTop from './components/back-to-top'
// import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <BackToTop/>
        {children}
      </body>
    </html>
  );
}
